CREATE TABLE player_leaderboard (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_name TEXT NOT NULL,
    timer NOT NULL,
    date_published TIMESTAMP DEFAULT now() NOT NULL
);